@baseUrl=http://localhost:5000/api/auth

POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "SalkaMessana",
    "email": "salka@messana.com",
    "password": "111055"
}

###
POST {{baseUrl}}/login
Content-Type: application/json
 
{
      "email": "patrizia@patti.com",
      "password":"12345678"
} 
