@baseUrl=http://localhost:5000/api/bookings

GET {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxODU2NzUsImV4cCI6MTcyNzIxNDQ3NX0.np3FkK7etpNDBI0Exp7aBcpnFg74L7T4Hju22thcNKE

###

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxOTUyMTYsImV4cCI6MTcyNzIyNDAxNn0.6EQx1jrNALyhMeUGobFkTLpXmlMwvxxQy0CzxJxc86g

{
    "customer": "66f021ecc3d4043796ef0459",
    "checkInDate": "2024-12-27",
    "checkOutDate": "2024-12-28",
    "room": "66ed9514fd35acb318a122c0",
    "pax": {
        "adults": 2,
        "children": 0
    },
    "status": "reserved",
    "totalPrice": ""
}

###

GET {{baseUrl}}/66f01747de008172b8a5c518
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxMzAxOTUsImV4cCI6MTcyNzE1ODk5NX0.S2FVzmdyQe3EkPGfzCbyVewU4n52gt4YeysaZH-CXKI

###

PUT {{baseUrl}}/66f0228bc3d4043796ef045e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxOTg5MjAsImV4cCI6MTcyNzIyNzcyMH0.H6Q2Zsca93gB5ksqGw51fGizxGG8-f7xDZyNayVoomU

{
    "customer": "66f021ecc3d4043796ef0459",
    "checkInDate": "2024-09-22",
    "checkOutDate": "2024-09-26",
    "room": "66ed9595fd35acb318a122d4",
    "pax": {
        "adults": 2,
        "children": 1
    },
    "status": "checkedIn"
}

###

DELETE {{baseUrl}}/66f1aa00999cf8489a268c2a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxMzAxOTUsImV4cCI6MTcyNzE1ODk5NX0.S2FVzmdyQe3EkPGfzCbyVewU4n52gt4YeysaZH-CXKI

###

GET {{baseUrl}}/todayarr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxMzAxOTUsImV4cCI6MTcyNzE1ODk5NX0.S2FVzmdyQe3EkPGfzCbyVewU4n52gt4YeysaZH-CXKI

###

GET {{baseUrl}}/todaydep
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxMzAxOTUsImV4cCI6MTcyNzE1ODk5NX0.S2FVzmdyQe3EkPGfzCbyVewU4n52gt4YeysaZH-CXKI

###

GET {{baseUrl}}/inhouse
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxMzAxOTUsImV4cCI6MTcyNzE1ODk5NX0.S2FVzmdyQe3EkPGfzCbyVewU4n52gt4YeysaZH-CXKI

###

GET {{baseUrl}}/booking-planning
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxOTUyMTYsImV4cCI6MTcyNzIyNDAxNn0.6EQx1jrNALyhMeUGobFkTLpXmlMwvxxQy0CzxJxc86g