@baseUrl=http://localhost:5000/api/bookings

GET {{baseUrl}}

###

POST {{baseUrl}}
Content-Type: application/json

{
    "customer": "66ed98d2a4652d0e175c1ccf",
    "checkInDate": "2024-09-20",
    "checkOutDate": "2024-09-25",
    "room": "66ed951cfd35acb318a122c2",
    "pax": {
        "adults": 2,
        "children": 0
    },
    "status": "reserved",
    "totalPrice": ""
}

###

GET {{baseUrl}}/66f01747de008172b8a5c518

###

PUT {{baseUrl}}/66f01b141c57b511708ef9fe
Content-Type: application/json

{
    "customer": "66ed98d2a4652d0e175c1ccf",
    "checkInDate": "2024-10-25",
    "checkOutDate": "2024-10-26",
    "room": "66ed957afd35acb318a122d0",
    "pax": {
        "adults": 2,
        "children": 0
    },
    "status": "reserved"
}

###

DELETE {{baseUrl}}/66f016e1de008172b8a5c510

###

GET {{baseUrl}}/todayarr
