@baseUrl=http://localhost:5000/api/bookings

GET {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmY0NGFkZWY3YmRlM2Q3OTQzOTdiYWEiLCJpYXQiOjE3MjcyODU5OTgsImV4cCI6MTcyNzMxNDc5OH0.5cjBYoYDTJOBuMWa8qNNzKJr5pxa0upvv5EN8zhxSzk

###

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmY1NWI4MzEwMDlkY2Y2ZWIzNGY5NGMiLCJpYXQiOjE3Mjc0NDk2MjksImV4cCI6MTcyNzQ3ODQyOX0.pSY1xQWYuzwfvwAlcd3nNVlxlX7FqUQtajQdPdTBOuQ

{
    "customer": "66f02224c3d4043796ef045b",
    "checkInDate": "2024-09-27",
    "checkOutDate": "2024-10-28",
    "room": "66ed94e4fd35acb318a122ba",
    "pax": {
        "adults": 1,
        "children": 0
    },
    "status": "reserved",
    "totalPrice": ""
}

###

GET {{baseUrl}}/66f01747de008172b8a5c518
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxMzAxOTUsImV4cCI6MTcyNzE1ODk5NX0.S2FVzmdyQe3EkPGfzCbyVewU4n52gt4YeysaZH-CXKI

###

PUT {{baseUrl}}/66f0228bc3d4043796ef045e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcyODExOTIsImV4cCI6MTcyNzMwOTk5Mn0.vstHOcK0YR4dsf4TMJiSrLOmS_C5qTb6iIHfgUOr99M

{
    "customer": "66ed98d2a4652d0e175c1ccf",
    "checkInDate": "2024-12-22",
    "checkOutDate": "2024-12-26",
    "room": "66ed955afd35acb318a122ca",
    "pax": {
        "adults": 2,
        "children": 1
    },
    "status": "checkedOut"
}

###

DELETE {{baseUrl}}/66f1aa00999cf8489a268c2a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxMzAxOTUsImV4cCI6MTcyNzE1ODk5NX0.S2FVzmdyQe3EkPGfzCbyVewU4n52gt4YeysaZH-CXKI

###

GET {{baseUrl}}/todayarr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmY1NWI4MzEwMDlkY2Y2ZWIzNGY5NGMiLCJpYXQiOjE3Mjc0NDk2MjksImV4cCI6MTcyNzQ3ODQyOX0.pSY1xQWYuzwfvwAlcd3nNVlxlX7FqUQtajQdPdTBOuQ

###

GET {{baseUrl}}/todaydep
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxMzAxOTUsImV4cCI6MTcyNzE1ODk5NX0.S2FVzmdyQe3EkPGfzCbyVewU4n52gt4YeysaZH-CXKI

###

GET {{baseUrl}}/inhouse
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmY1NWI4MzEwMDlkY2Y2ZWIzNGY5NGMiLCJpYXQiOjE3Mjc0NDk2MjksImV4cCI6MTcyNzQ3ODQyOX0.pSY1xQWYuzwfvwAlcd3nNVlxlX7FqUQtajQdPdTBOuQ

###

GET {{baseUrl}}/booking-planning
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVjMjM4ODIzNDk3MGZjNTk2MzAxZDAiLCJpYXQiOjE3MjcxOTUyMTYsImV4cCI6MTcyNzIyNDAxNn0.6EQx1jrNALyhMeUGobFkTLpXmlMwvxxQy0CzxJxc86g