@baseUrl=http://localhost:5000/api/customers

POST {{baseUrl}}
Content-Type: application/json

{
    "name": "Andrea",
    "surname": "Ruocco",
    "email": "andrea@ruocco.com",
    "phone": "111111111",
    "dateOfBirth": "1996-06-21"
}

###

GET {{baseUrl}}

###

GET {{baseUrl}}/66ed98d2a4652d0e175c1ccf


###

PUT {{baseUrl}}/66ed98d2a4652d0e175c1ccf
Content-Type: application/json

{
    "name": "Martina",
    "surname": "Patti",
    "email": "martina@patti.com",
    "phone": "88888888",
    "dateOfBirth": "1987-08-12"
}

###

DELETE {{baseUrl}}/66f2e4e717514644ad6f4c9f