@baseUrl=http://localhost:5000/api/rooms

GET {{baseUrl}}

###

POST {{baseUrl}}
Content-Type: application/json

{
    "roomNumber": "305",
    "type": "Family",
    "price": "190",
    "status": "available",
    "maxPax": "4"
}

###

GET {{baseUrl}}/66ed955afd35acb318a122ca

###

PUT {{baseUrl}}/66ed959dfd35acb318a122d8
Content-Type: application/json

{
    "roomNumber": "304",
    "type": "Family",
    "price": "190",
    "status": "available",
    "maxPax": 4
}

###

DELETE {{baseUrl}}/66f2f40e8e01de9b6f758a47

###

GET {{baseUrl}}/availableRoom